/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mybatis_test;

import dao.*;

import model.*;

import java.io.*;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.*;

// XML 없이 SqlSessionFactory 생성 
        
/*
    DataSource dataSource = 데이터 소스 따로 생성
    TransactionFactory transactionFactory = new JdbcTransactionFactory();
    Environment environment = new Environment("development", transactionFactory, dataSource);
    Configuration configuration = new Configuration(environment);
    configuration.addMapper(User.class);
    SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(configuration);
*/

public class App {
    public static void main(String[] args) {
        String resource = "mybatis-config.xml";

        InputStream inputStream = null;
        
        try {
            inputStream = Resources.getResourceAsStream(resource);
        } catch(IOException e) {

        }

        SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
        
        // 트랜잭션 경계(try ~ resource 문 사용)
        try(SqlSession sqlSession = sqlSessionFactory.openSession()) {
            int userCount = sqlSession.selectOne("mapper.UserMapper.countUser", "1");

            System.out.println("User Count : " + userCount);

            if( userCount == 0 ) {
                sqlSession.insert("mapper.UserMapper.insertUser", new User("1", "1", "1"));
            }

            User user = sqlSession.selectOne("mapper.UserMapper.selectUser", "1");

            System.out.println(user);

            user.setUserName("1(수정)");

            sqlSession.update("mapper.UserMapper.updateUser", user);
            
            User user2 = sqlSession.selectOne("mapper.UserMapper.selectUser", "1");

            System.out.println(user2);
            
            sqlSession.delete("mapper.UserMapper.deleteUser", "1");

            userCount = sqlSession.selectOne("mapper.UserMapper.countUser", "1");

            System.out.println("User Count(Delete After) : " + userCount);

            sqlSession.commit();
        }
    }
}
